version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www/html
    ports:
      - "80:80"
    volumes:
      - ./index.php:/var/www/html/index.php
      - ./default.conf:/etc/nginx/http.d/default.conf
      - ./supervisord.conf:/etc/supervisord.conf
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
